# Generated by Django 4.1.2 on 2022-11-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('authors_profile', models.URLField()),
                ('authors_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('reply_subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
            ],
        ),
    ]
