# Generated by Django 4.1.2 on 2022-11-13 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moodleglue', '0002_course_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionslog',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moodleglue.course'),
        ),
    ]
