# Generated by Django 4.1.2 on 2022-11-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodleglue', '0005_discussionslog_answer_discussionslog_dislike_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionslog',
            old_name='processed',
            new_name='replied',
        ),
        migrations.AddField(
            model_name='discussionslog',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
