# Generated by Django 4.1.2 on 2022-11-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodleglue', '0007_rename_name_course_fullname_course_displayname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='timemodified',
            field=models.BigIntegerField(default=0),
        ),
    ]
