# Generated by Django 4.1.2 on 2022-11-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodleglue', '0008_course_timemodified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionslog',
            name='id',
        ),
        migrations.AddField(
            model_name='discussionslog',
            name='replyid',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
