# Generated by Django 4.1.2 on 2022-11-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodleglue', '0009_remove_discussionslog_id_discussionslog_replyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionslog',
            name='id',
            field=models.IntegerField(default=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussionslog',
            name='replyid',
            field=models.IntegerField(unique=True),
        ),
    ]
