# Generated by Django 4.1.2 on 2022-11-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodleglue', '0012_extractedcontexts_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionslog',
            name='replyid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
