# Generated by Django 4.1.2 on 2022-11-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodleglue', '0013_alter_discussionslog_replyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedcontexts',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedcontexts',
            name='heading_order',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='extractedcontexts',
            name='index',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='extractedcontexts',
            name='page_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='extractedcontexts',
            name='topic',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
